flowchart TB
    A["Entradas"] --> B["Multiplicar por pesos"]
    B --> C["Sumar por nodo oculto"]
    C --> D["Función de activación"]
    D --> E["Multiplicar por pesos de salida"]
    E --> F["Sumar y activar salida"]
    F --> G["Predicción"]

     A:::Aqua
     B:::Sky
     C:::Peach
     D:::Ash
     E:::Sky
     F:::Peach
     G:::Rose
    classDef Aqua stroke-width:1px, stroke-dasharray:none, stroke:#46EDC8, fill:#DEFFF8, color:#378E7A
    classDef Rose stroke-width:1px, stroke-dasharray:none, stroke:#FF5978, fill:#FFDFE5, color:#8E2236
    classDef Sky stroke-width:1px, stroke-dasharray:none, stroke:#374D7C, fill:#E2EBFF, color:#374D7C
    classDef Peach stroke-width:1px, stroke-dasharray:none, stroke:#FBB35A, fill:#FFEFDB, color:#8F632D
    classDef Ash stroke-width:1px, stroke-dasharray:none, stroke:#999999, fill:#EEEEEE, color:#000000