mindmap
  root((ANNs))
    Inspiración biológica
    Perceptrón
    Forward propagation
    Backpropagation
    Funciones de activación
    Diseño
      Pesos
      Capas
      Tasa aprendizaje
    Tipos
      RNN
      CNN
      GAN