---
config:
  layout: dagre
---
flowchart LR
    X["Tamaño de casa"] -- Entrada --> M["Modelo Lineal"]
    M -- Salida --> Y["Precio"]

     X:::Aqua
     M:::Sky
     Y:::Rose
    classDef Aqua stroke-width:1px, stroke-dasharray:none, stroke:#46EDC8, fill:#DEFFF8, color:#378E7A
    classDef Sky stroke-width:1px, stroke-dasharray:none, stroke:#374D7C, fill:#E2EBFF, color:#374D7C
    classDef Rose stroke-width:1px, stroke-dasharray:none, stroke:#FF5978, fill:#FFDFE5, color:#8E2236